config/routes.rb
Rails.application.routes.draw do
  get 'index/index'
  devise_for :users
  resources :actividades
  resources :alumnos
  resources :docentes
  resources :tipos
  resources :carreras
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#index"
end

app/models/carrera.rb
class Carrera < ApplicationRecord
end

app/controllers/carreras_controller.rb
class CarrerasController < ApplicationController
  before_action :set_carrera, only: %i[ show edit update destroy ]

  # GET /carreras or /carreras.json
  def index
    @carreras = Carrera.all
  end

  # GET /carreras/1 or /carreras/1.json
  def show
  end

  # GET /carreras/new
  def new
    @carrera = Carrera.new
  end

  # GET /carreras/1/edit
  def edit
  end

  # POST /carreras or /carreras.json
  def create
    @carrera = Carrera.new(carrera_params)

    respond_to do |format|
      if @carrera.save
        format.html { redirect_to carrera_url(@carrera), notice: "Carrera was successfully created." }
        format.json { render :show, status: :created, location: @carrera }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carreras/1 or /carreras/1.json
  def update
    respond_to do |format|
      if @carrera.update(carrera_params)
        format.html { redirect_to carrera_url(@carrera), notice: "Carrera was successfully updated." }
        format.json { render :show, status: :ok, location: @carrera }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carreras/1 or /carreras/1.json
  def destroy
    @carrera.destroy

    respond_to do |format|
      format.html { redirect_to carreras_url, notice: "Carrera was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrera
      @carrera = Carrera.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def carrera_params
      params.require(:carrera).permit(:carrera)
    end
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/views/carreras/_carrera.html.erb
<div id="<%= dom_id carrera %>">
  <p>
    <strong>Carrera:</strong>
    <%= carrera.carrera %>
  </p>

</div>

app/views/carreras/_form.html.erb
<%= form_with(model: carrera) do |form| %>
  <% if carrera.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(carrera.errors.count, "error") %> prohibited this carrera from being saved:</h2>

      <ul>
        <% carrera.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :carrera, style: "display: block" %>
    <%= form.text_field :carrera %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carreras/edit.html.erb
<h1>Editing carrera</h1>

<%= render "form", carrera: @carrera %>

<br>

<div>
  <%= link_to "Show this carrera", @carrera %> |
  <%= link_to "Back to carreras", carreras_path %>
</div>

app/views/carreras/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carreras</h1>

<div id="carreras">
  <% @carreras.each do |carrera| %>
    <%= render carrera %>
    <p>
      <%= link_to "Show this carrera", carrera %>
    </p>
  <% end %>
</div>

<%= link_to "New carrera", new_carrera_path %>

app/views/carreras/new.html.erb
<h1>New carrera</h1>

<%= render "form", carrera: @carrera %>

<br>

<div>
  <%= link_to "Back to carreras", carreras_path %>
</div>

app/views/carreras/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @carrera %>

<div>
  <%= link_to "Edit this carrera", edit_carrera_path(@carrera) %> |
  <%= link_to "Back to carreras", carreras_path %>

  <%= button_to "Destroy this carrera", @carrera, method: :delete %>
</div>