config/routes.rb
Rails.application.routes.draw do
  get 'index/index'
  devise_for :users
  resources :actividades
  resources :alumnos
  resources :docentes
  resources :tipos
  resources :carreras
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#index"
end

app/models/alumno.rb
class Alumno < ApplicationRecord
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: %i[ show edit update destroy ]

  # GET /alumnos or /alumnos.json
  def index
    @alumnos = Alumno.all
  end

  # GET /alumnos/1 or /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos or /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to alumno_url(@alumno), notice: "Alumno was successfully created." }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1 or /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to alumno_url(@alumno), notice: "Alumno was successfully updated." }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1 or /alumnos/1.json
  def destroy
    @alumno.destroy

    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: "Alumno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alumno_params
      params.require(:alumno).permit(:nombre, :numero_de_control, :semestre, :carrera)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/views/alumnos/_alumno.html.erb
<div id="<%= dom_id alumno %>">
  <p>
    <strong>Nombre:</strong>
    <%= alumno.nombre %>
  </p>

  <p>
    <strong>Numero de control:</strong>
    <%= alumno.numero_de_control %>
  </p>

  <p>
    <strong>Semestre:</strong>
    <%= alumno.semestre %>
  </p>

  <p>
    <strong>Carrera:</strong>
    <%= alumno.carrera %>
  </p>

</div>

app/views/alumnos/_form.html.erb
<%= form_with(model: alumno) do |form| %>
  <% if alumno.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
        <% alumno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :numero_de_control, style: "display: block" %>
    <%= form.number_field :numero_de_control %>
  </div>

  <div>
    <%= form.label :semestre, style: "display: block" %>
    <%= form.number_field :semestre %>
  </div>

  <div>
    <%= form.label :carrera, style: "display: block" %>
    <%= form.text_field :carrera %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/alumnos/edit.html.erb
<h1>Editing alumno</h1>

<%= render "form", alumno: @alumno %>

<br>

<div>
  <%= link_to "Show this alumno", @alumno %> |
  <%= link_to "Back to alumnos", alumnos_path %>
</div>

app/views/alumnos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Alumnos</h1>

<div id="alumnos">
  <% @alumnos.each do |alumno| %>
    <%= render alumno %>
    <p>
      <%= link_to "Show this alumno", alumno %>
    </p>
  <% end %>
</div>

<%= link_to "New alumno", new_alumno_path %>

app/views/alumnos/new.html.erb
<h1>New alumno</h1>

<%= render "form", alumno: @alumno %>

<br>

<div>
  <%= link_to "Back to alumnos", alumnos_path %>
</div>

app/views/alumnos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @alumno %>

<div>
  <%= link_to "Edit this alumno", edit_alumno_path(@alumno) %> |
  <%= link_to "Back to alumnos", alumnos_path %>

  <%= button_to "Destroy this alumno", @alumno, method: :delete %>
</div>