config/routes.rb
Rails.application.routes.draw do
  get 'index/index'
  devise_for :users
  resources :actividades
  resources :alumnos
  resources :docentes
  resources :tipos
  resources :carreras
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#index"
end

app/models/docente.rb
class Docente < ApplicationRecord
end

app/controllers/docentes_controller.rb
class DocentesController < ApplicationController
  before_action :set_docente, only: %i[ show edit update destroy ]

  # GET /docentes or /docentes.json
  def index
    @docentes = Docente.all
  end

  # GET /docentes/1 or /docentes/1.json
  def show
  end

  # GET /docentes/new
  def new
    @docente = Docente.new
  end

  # GET /docentes/1/edit
  def edit
  end

  # POST /docentes or /docentes.json
  def create
    @docente = Docente.new(docente_params)

    respond_to do |format|
      if @docente.save
        format.html { redirect_to docente_url(@docente), notice: "Docente was successfully created." }
        format.json { render :show, status: :created, location: @docente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docentes/1 or /docentes/1.json
  def update
    respond_to do |format|
      if @docente.update(docente_params)
        format.html { redirect_to docente_url(@docente), notice: "Docente was successfully updated." }
        format.json { render :show, status: :ok, location: @docente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docentes/1 or /docentes/1.json
  def destroy
    @docente.destroy

    respond_to do |format|
      format.html { redirect_to docentes_url, notice: "Docente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docente
      @docente = Docente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def docente_params
      params.require(:docente).permit(:nombre)
    end
end

app/helpers/docentes_helper.rb
module DocentesHelper
end

app/views/docentes/_docente.html.erb
<div id="<%= dom_id docente %>">
  <p>
    <strong>Nombre:</strong>
    <%= docente.nombre %>
  </p>

</div>

app/views/docentes/_form.html.erb
<%= form_with(model: docente) do |form| %>
  <% if docente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(docente.errors.count, "error") %> prohibited this docente from being saved:</h2>

      <ul>
        <% docente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/docentes/edit.html.erb
<h1>Editing docente</h1>

<%= render "form", docente: @docente %>

<br>

<div>
  <%= link_to "Show this docente", @docente %> |
  <%= link_to "Back to docentes", docentes_path %>
</div>

app/views/docentes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Docentes</h1>

<div id="docentes">
  <% @docentes.each do |docente| %>
    <%= render docente %>
    <p>
      <%= link_to "Show this docente", docente %>
    </p>
  <% end %>
</div>

<%= link_to "New docente", new_docente_path %>

app/views/docentes/new.html.erb
<h1>New docente</h1>

<%= render "form", docente: @docente %>

<br>

<div>
  <%= link_to "Back to docentes", docentes_path %>
</div>

app/views/docentes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @docente %>

<div>
  <%= link_to "Edit this docente", edit_docente_path(@docente) %> |
  <%= link_to "Back to docentes", docentes_path %>

  <%= button_to "Destroy this docente", @docente, method: :delete %>
</div>