config/routes.rb
Rails.application.routes.draw do
  get 'index/index'
  devise_for :users
  resources :actividades
  resources :alumnos
  resources :docentes
  resources :tipos
  resources :carreras
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#index"
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: %i[ show edit update destroy ]

  # GET /tipos or /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1 or /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos or /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to tipo_url(@tipo), notice: "Tipo was successfully created." }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1 or /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to tipo_url(@tipo), notice: "Tipo was successfully updated." }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1 or /tipos/1.json
  def destroy
    @tipo.destroy

    respond_to do |format|
      format.html { redirect_to tipos_url, notice: "Tipo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_params
      params.require(:tipo).permit(:deportivo, :cultural)
    end
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipos/_form.html.erb
<%= form_with(model: tipo) do |form| %>
  <% if tipo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
        <% tipo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :deportivo, style: "display: block" %>
    <%= form.check_box :deportivo %>
  </div>

  <div>
    <%= form.label :cultural, style: "display: block" %>
    <%= form.check_box :cultural %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tipos/_tipo.html.erb
<div id="<%= dom_id tipo %>">
  <p>
    <strong>Deportivo:</strong>
    <%= tipo.deportivo %>
  </p>

  <p>
    <strong>Cultural:</strong>
    <%= tipo.cultural %>
  </p>

</div>

app/views/tipos/edit.html.erb
<h1>Editing tipo</h1>

<%= render "form", tipo: @tipo %>

<br>

<div>
  <%= link_to "Show this tipo", @tipo %> |
  <%= link_to "Back to tipos", tipos_path %>
</div>

app/views/tipos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tipos</h1>

<div id="tipos">
  <% @tipos.each do |tipo| %>
    <%= render tipo %>
    <p>
      <%= link_to "Show this tipo", tipo %>
    </p>
  <% end %>
</div>

<%= link_to "New tipo", new_tipo_path %>

app/views/tipos/new.html.erb
<h1>New tipo</h1>

<%= render "form", tipo: @tipo %>

<br>

<div>
  <%= link_to "Back to tipos", tipos_path %>
</div>

app/views/tipos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tipo %>

<div>
  <%= link_to "Edit this tipo", edit_tipo_path(@tipo) %> |
  <%= link_to "Back to tipos", tipos_path %>

  <%= button_to "Destroy this tipo", @tipo, method: :delete %>
</div>